spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1062753642703-6q4evbgpco0et7t6s7u468b7vj04hi6q.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          kakao:
            client-id: 081f3008391be26425af52589ac18543
            client-name: Kakao
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # http://54.180.12.194:8080/  login/  oauth2/code/    kakao
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
          naver:
            client-id: ayExhYqaL4SkNW3V3UiP
            client-secret: jp32AxmoQ5
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri:  https://nid.naver.com/oauth2.0/token
            user-info-uri:  https://openapi.naver.com/v1/nid/me
            user-name-attribute:  response

